/// @description Returns the depth of the specified object.
/// @param {Number} obj The index of the object to check
/// @return {Number} depth of the object
function object_get_depth(argument0) {

	switch(argument0) {
        case objCloudTransition:
        case objEnterFFZ:
        case objEnterTTZF:
        case objEnterUFO:
        case objFade:
        case objFadeWhite:
        case objFadeWhiteFromSave:
        case objFadeWhiteFromSaveToTitle:
        case objFadeWhiteFromLevelToTitle:
        case objFadeWhiteFromSpecialStageToTitle:
        case objFinalEnding:
        case objLevelToSS:
        case objSSToLevel:
        case objSSZEndTransition:
        case objTitlecard:
        case objTitlecardDisolve:
        case objTitleCardFFZ:
        case objTitleCardSSZ:
        case objTTZ2Transition:
        case objSSToScore:
            return -2048;
        case objScoreCardFake:
        case objMenu:
        case objScoreCard:
            return -1028;
        case objTimeTravel:
            return -1027;
        case objTitleControl:
        case objGameOver:
        case objHud:
        case objInputHelp:
        case objSSHud:
        case objSSMessages:
            return -1026;
        case objMetallixController:
        case objScreen:
        case objTextEnding:
            return -1024;
        case objSSScoreCard:
            return -1023;
        case objSSEmerald:
            return -1000;
        case objGolemTarget:
            return -128;
        case objField:
        case objMetalElectric:
            return -50;
        case objGalanikShadow:
        case objEndingExplode:
        case objLillyPad:
        case objMetalThrow:
            return -20;
        case objSauceroid:
        case objSauceroidFire:
            return -16;
        case objEggWalkerLaser:
        case objMetallixLaser:
        case objUFOFlame:
            return -11;
        case objEggWalkerGun:
        case objEggWalkerGunCover:
        case objEggWalkerLeg:
        case objSnailTrail:
        case objSquibotGunCover:
        case objExampleBridge:
        case objExampleQuicksand:
        case objBridge:
        case objStart:
        case objUFO:
            return -10;
        case objAA1BossLaser:
        case objSquibotLaser:
            return -9;
        case objAA1Boss:
        case objBubblesRegion:
        case objDragonFly:
        case objSquibotGun:
        case objLavaFountain:
        case objWaterfall:
            return -8;
        case objDragonFlySegment:
        case objLavaStream:
        case objSSMetalSonic:
            return -7;
        case objAA1BossFloor:
        case objSSCaterminator:
        case objSSCaterminatorOrb:
            return -5;
        case objExplosionGroup:
        case objExplosionGroupNoSound:
        case objMetalBackFull:
            return -4;
        case objCapsuleSpark:
        case objLavaCrack:
        case objTTFMovingFloor:
        case objTTFMovingFloorChild:
            return -3;
        case objAALampLight:
        case objSlotMachine:
        case objLaserFire:
        case objFireFlyLight:
        case objDDLeaf:
        case objFireball:
        case objOstrichDibris:
        case objLava:
        case objLavaSeep:
        case objDustCloud:
        case objMagnet:
        case objVVBushes:
        case objVVLeaf:
            return -2;
        case objAABoostWheel:
        case objAACloud:
        case objAACloud2:
        case objAASpinner:
        case objEggWalkerMoleDeath:
        case objSmokePuff:
        case objMetallixPlatformHarmful:
        case objMegaTrooperMoleDeath:
        case objLargeRockFinalBoss:
        case objPPBossFloor:
        case objFireFly:
        case objDDBreakableRock:
        case objSand:
        case objSpinFlame:
        case objCaterkiller:
        case objDragonFlyBomb:
        case objSmallBomb:
        case objFFLift:
        case objBubble:
        case objTitleCloud0:
        case objTitleCloud1:
        case objTitleRingOverlay:
        case objLargeRock:
        case objSSLevelChunks:
        case objCanon:
        case objCanonSmoke:
        case objGlassBottom:
        case objGlassTop:
        case objIntroMetalBack:
        case objIntroMetalProfile:
        case objIntroMetalZoom:
        case objPyramidJump:
        case objSSRing:
        case objSSBoost:
        case objSSLife:
        case objSSController:
        case objMagnetSparkle:
        case objShocker:
        case objShockerTop:
        case objVVBomb:
        case objVVBombLarge:
        case objVVBreakableWall:
            return -1;
        case objAABobbin:
        case objAABumper:
        case objAABumperV:
        case objAADropBumper:
        case objAAFlipper:
        case objAAKnuckles:
        case objAAPlane:
        case objAAPlatform:
        case objAAShockBumper:
        case objAAShocker:
        case objAATrampoline:
        case objBallSplash:
        case objInvisiblePlatform:
        case objAAFutureBack:
        case objAAPastBack:
        case objAA1BossController:
        case objEggWalkerBossController:
        case objEggWalkerBossSensor:
        case objMoleEggWalker:
        case objSmokeSpawn:
        case objMetallixHead:
        case objUFOAttackDD:
        case objMegaTrooperController:
        case objMegaTrooperGround:
        case objMegaTrooperGroundPart:
        case objMegaTrooperHand:
        case objFinalBossController:
        case objFinalBossFireball:
        case objFinalBossFireBallStatic:
        case objFinalBossLaser:
        case objFinalBossPathControl:
        case objPPBossController:
        case objGolemArm:
        case objHarmfulBlock:
        case objTTBossController:
        case objVV1Boss:
        case objVV1BossController:
        case objVV1BossSign:
        case objFireFlyBossController:
        case objFireFlyLightShot:
        case objMetalSonicFlyOff:
        case objMetalSonicUFOs:
        case objUFOAttack:
        case objUFOCharge:
        case objDDFutureBack:
        case objDDFutureBackAct2:
        case objDDFutureIndoorBack:
        case objDDFutureIndoorBackAct2:
        case objDDPastBack:
        case objConveyor:
        case objDDFFanPlatform:
        case objDDRockPiece:
        case objFan:
        case objPlaneGimmick:
        case objPlaneStop:
        case objSkydive:
        case objSpinFanHarmful:
        case objSpinFlamesEmmit:
        case objBubblesBadnik:
        case objCaterkillerOrb:
        case objCaterminator:
        case objFlowerShot:
        case objMoleGun:
        case objMoleGunFire:
        case objMoleYoyo:
        case objMoleYoyoYoyo:
        case objOrbinaut:
        case objOrbinautOrb:
        case objOstrich:
        case objAntnik:
        case objBigBombBadnik:
        case objDinobot:
        case objEagleBot:
        case objEagleBotIdle:
        case objEnemyTurn:
        case objFireTorch:
        case objLaserGun:
        case objLaserShot:
        case objRhinobot:
        case objSealBomb:
        case objSealbot:
        case objWaspBot:
        case objWhalebot:
        case objPterodactyl:
        case objPterodactylBomb:
        case objRoboRexFrontFoot:
        case objRoboRexHead:
        case objSnailbot:
        case objSquibot:
        case objExampleBreakable:
        case objExampleBreakableDebris:
        case objExampleMovingPlatformHorz:
        case objMovingHorVerPlatform:
        case objExampleMovingPlatformVert:
        case objPushLog:
        case objFFPastBack:
        case objFFPastBackAct2:
        case objFFCollapsingPlatform:
        case objFFCollapsingPlatformPiece:
        case objFFOrb:
        case objFFOrbLarge:
        case objFFSnowFan:
        case objSnowBlowerVTop:
        case objFFSpikeball:
        case objBoard:
        case objBoardExit:
        case objFFDropSpike:
        case objArmor:
        case objGameData:
        case objInput:
        case objInputMethodDependant:
        case objMusic:
        case objResources:
        case objCapsuleDebris:
        case objBoost:
        case objCutscene:
        case objLayerFlip:
        case objLayerSet:
        case objPath:
        case objBoss:
        case objEnemy:
        case objEnemyAlwaysActive:
        case objBumper:
        case objFlower:
        case objFlowerSpark:
        case objScorePopup:
        case objMetalSonicVoice:
        case objExplosionCluster:
        case objExplosionSpecial:
        case objRingDropped:
        case objBubbleCluster:
        case obj3dLayerFlip:
        case obj3DSlant:
        case objLevel:
        case objMonitor:
        case objPathSplitStall:
        case objRing:
        case objRingGiant:
        case objSpikesNonSolid:
        case objCharacterSelect:
        case objTitleSonic:
        case objTransition:
        case objTransitionDisabledControls:
        case objSaveSlot:
        case objDeleteSlot:
        case objNoSaveSlot:
        case objSaveControl:
        case objBreakableRockBits:
        case objBreakableRocks:
        case objCrateLong:
        case objFallingBlocks:
        case objLavaRock:
        case objLavaTop:
        case objScurge:
        case objSingleFallBlock:
        case objSmallRock:
        case objRRFBack:
        case objRRPBack:
        case objArrowChild:
        case objArrowSpawn:
        case objGlassBreak:
        case objRRBreakableColumn:
        case objRRWallRun:
        case objSwing:
        case objRRWind:
        case objRRLeaf:
        case objIntro1Control:
        case objIntroClouds:
        case objIntroIsland:
        case objIntroLittlePlanet:
        case objPyramid:
        case objPyramidBack:
        case objPyramidRotate:
        case objBadnikCutscene:
        case objCutEmeralds:
        case objCutsceneController:
        case objDeathEggCut:
        case objFadeInWhite:
        case objIntroIslandPast:
        case objKnucklesIntroPast:
        case objKnucklesLight:
        case objMetalSonicWarped:
        case objRobotnikPastIntro:
        case objSmallSonic:
        case objSonicIntroPast:
        case objSonicKnuckles:
        case objSonicLight:
        case objTailsFlyCut:
        case objTailsIntroPast:
        case objTailsLight:
        case objCredits:
        case objGalacnikFootPart:
        case objGalacnikHandPart:
        case objGalacnikStatchPart:
        case objTLPRestoreEnding:
        case objNonSolid:
        case objSceneObject:
        case objSolid:
        case objShieldEarth_Rock:
        case objShieldEarth:
        case objShieldIce:
        case objShieldIceAttack:
        case objShieldIceBlockDebris:
        case objShieldBubble:
        case objShieldFlame:
        case objShieldLightning:
        case objShieldWind:
        case objDashSmoke:
        case objFallHat:
        case objInstaShield:
        case objInvincibility:
        case objShield:
        case objTailsEffect:
        case objWaterWave:
        case objCamera:
        case objEffect:
        case objPlayer:
        case obj3DExplosion:
        case objMissileFire:
        case objSSEnemy:
        case objSSMole:
        case objSSMoleMissile:
        case objSSWhalebot:
        case objSSBumper:
        case objSSSpikeBall:
        case objSSRingFly:
        case objSSEnd:
        case objSSLevel:
        case objSSParent:
        case objSSPlayer:
        case objSSPlayerLandingTracker:
        case Solid:
        case objHiddenSpring:
        case objSpring:
        case objSpringDiagonal:
        case objSpringGreen:
        case objSpringRed:
        case objSpringRedDiagonal:
        case objSSRobotnik:
        case objPaddleSwitch:
        case objPongController:
        case objSwitchButton:
        case objSpark:
        case objSparkCannon:
        case objConveyerAngled:
        case objShockerLaser:
        case objSSPlatformVertical:
        case objBlock:
        case objCurveConcave:
        case objCurveConcaveSlim:
        case objCurveConvex:
        case objCurveConvexSlim:
        case objSlant:
        case objTTPastBackParent:
        case objCrate:
        case objFallingLog:
        case objFallingLogVanish:
        case objSpikeRoller:
        case objSpikeRollerHarmful:
        case objTTSwingWhere:
        case objWaterJetEmmiter:
        case objWaterJetEmmiterTripple:
        case objVVBombExplosion:
        case objVVCSCField:
        case objVVCSCurveConcave:
        case objMetalThrowController:
        case objUFOLead:
        case objVVRhinobotSpawn:
        case objVVRhinobotSpawnDebris:
        case objVVMask01:
        case objOldManOwl:
        case objVVBreakableWallDebris:
        case objVVPlatform:
        case objVVDoor:
        case objVVFutureBack:
        case objVVFutureBackAct2:
        case objVVPastBack:
        case objVVPastBack2:
        case objBGSlots:
        case objAAShockSwingH:
        case objAAShockSwingV:
        case objEggWalker:
        case objMetallixPlatform:
        case objMegaTrooperEye:
        case objFinalBossArm:
        case objFinalBossFace:
        case objRingDroppedFinalBoss:
        case objRingFinalBoss:
        case objBossPlatform:
        case objVV1BossBroken:
        case objVV1BossFlyingPlatform:
        case objFireFlyGraphic:
        case objDDFallingPlatform:
        case objDDFallingPlatformSpawed:
        case objCaterminatorOrb:
        case objFireRinobot:
        case objRoboRex:
        case objWarp:
        case objRingMagnetized:
        case objFallingPlatform:
        case objSignPost:
        case objSignPostAct2:
        case objLampPost:
        case objTitleDynamo:
        case objRockStairs:
        case objAASwing:
        case objArrowParent:
        case objLittlePlanetPiece1:
        case objLittlePlanetPiece2:
        case objLittlePlanetPiece3:
        case objSSMetalCut:
        case objPaddle:
        case objPaddleTop:
        case objUFOFan:
        case objWaterJet:
        case objWaterJetTripple:
        case objVVBombLauncher:
        case objVVTileHole:
            return 1;
        case objSlotMachineSolidMask:
        case objAASwingWheel:
        case objAATargetSwing:
        case objAAClock:
        case objMetallix:
        case objMegaTrooperJaw:
        case objFinalBoss:
        case objFinalBossBackArm:
        case objPPGalanikLaser:
        case objMoleFan:
        case objSnowBlowerV:
        case objFFSwingWheel:
        case objTitlescreenPlane:
        case objBiPlane:
        case objPlaneRestoreFinal:
        case objSSScreen:
            return 2;
        case objMegaTrooperHead:
        case objGalanikFireball:
        case objOstrichHead:
        case objIcon:
        case objTitleEffects:
        case objTitleRing:
        case objGalanikBadEnding:
        case objGalanikFloat:
            return 3;
        case objAASmasherSmall:
        case objMegaTrooperDriver:
        case objMegaTrooperOrb:
        case objWhaleBossJaw:
        case objWhaleFin:
        case objFFIceSlip:
        case objSpike:
        case objTimePost:
        case objTitleLighting:
        case objCharacterFall:
        case objFlippingPlatform:
        case objTTFFallingPlatform:
            return 4;
        case objMegaTrooperShoulder:
        case objMetalDamage:
        case objWhaleBoss:
            return 5;
        case objMegaTrooperHeadBack:
        case objPPBossDisapearPlatform:
        case objAmyEnding:
            return 6;
        case objGalanikNose:
        case objCapsule:
        case objMonitorBroken:
            return 7;
        case objGalanik:
        case objGalanikSmall:
        case objPollPlatform:
        case objPollPlatformReverse:
        case objCapsuleGlass:
            return 8;
        case objSpinPoll:
        case objSpinPollReverse:
            return 9;
        case objMegaTrooper:
        case objGolemHand:
        case objWhaleBossTowardsCam:
        case objVV1BossShield:
        case objRoboRexFoot:
        case objTimeTravelVortex:
        case objNeverLakeEnding:
        case objTubeWater:
        case objVVShip:
        case objVVShipLarge:
        case objVVShipMedium:
        case objVVShipMediumStationary:
            return 10;
        case objSpringBlock:
            return 12;
        case objTTPWave:
            return 13;
        case objWater:
        case objDynamoDeath:
            return 16;
        case objTTPastShip:
            return 17;
        case objTitleWater:
            return 20;
        case objSSCamera:
            return 101;
        case objMetallixUFOBg:
        case objUFOBg:
            return 120;
        case objGolem:
        case objGolemOrb:
            return 128;
        case objFinalBossBackground:
        case objFFFutureBack:
        case objFFFutureBackAct2:
        case objPPBackground:
        case objSSBack:
            return 1000;
        case objVVPastBackSun:
            return 1023;
        case objAA1BossFloorBack:
        case objDDFutureBackSun:
        case objDDPSaturn:
        case objParallax:
        case objPPBackEarth:
        case objLittlePlanetPast:
        case objBigLittlePlanet:
        case objTTFutureBack:
        case objTTFutureBack2:
        case objTTFutureRig:
        case objTTFutureRig2:
        case objTTPastBack:
        case objTTPastBack2:
        case objTTPastShipMedium:
        case objTTPastShipSmall:
            return 1024;
        case objAA1BossFutureBack:
        case objAA1BossPastBack:
        case objSSZBGParallax:
        case objSSZBGParallax2:
        case objSSZBGParallax3:
        case objSSZBGParallax4:
            return 1025;
        case objSSPastTrack1BG:
            return 2000;
		default:
			return 0;
	}
}
